### ISSUE TITLE
Prometheus exporter only exporting python_gc Metrics

### ISSUE THREAD

**Issue by ThoughtfulDev** [fkie-cad/Logprep#423]
When starting Logprep with activated prometheus metric as per instructions on the wiki page the metrics only show internal python metrics.

**Expected behavior**
Prometheus exporter also shows metrics about processes log messages (logs per second, processed logs). (similiar to stdout)

**Current behavior**
Only exporting metrics for example
```
python_gc_objects_collected_total
python_gc_objects_uncollectable_total
[...and much more internal python ones]
```

**Steps to reproduce**
1. Start Logprep with metric enabled and prometheus enabled as per documentation

**Environment**

Logprep version: latest
Python version: 3.11
Enviroment: Kubernetes with containerd

**Comment by dtrai2** [comment]
The logprep prometheus metrics will only be printed once an event is actually processed. Did you see the logging output `Started exposing metrics`? If not then there wasn't probably a processing of events yet. If you saw this log output and still don't have prometheus metrics, then we have to investigate further.

**Comment by ThoughtfulDev** [comment]
The logprep containers are running for about 24hours now. Im seing `Prometheus Exporter started on port 80`
Events are being processed judging by the `Processed events per 30 seconds: 48573` (and successfully arrive at opensearch)

**Comment by dtrai2** [comment]
I think I have identified the problem. In a recent change we made the environment variable `PROMETHEUS_MULTIPROC_DIR` optional by setting it inside python. Seems though that this doesn't propagate to `prometheus_client` python library as it requires it as an actual environment variable. Meaning the logprep documentation is currently wrong and it is still mandatory to set the variable `PROMETHEUS_MULTIPROC_DIR` manually, before the start of logprep. Could you try and see if that fixes your issue? I will update the documentation then accordingly.

**Comment by ThoughtfulDev** [comment]
i just tested it by setting `PROMETHEUS_MULTIPROC_DIR` to `/tmp/prometheus`
The folder does get created but not filled with any files. The metrics also just as before only show python and process info even after validating that logprep does indeed process events.

**Comment by dtrai2** [comment]
Okay thanks for testing that, it's all just a bit odd as the metrics seem to work quite well in the main branch. Could you please verify if the following steps/setup work for you:

1. clone the repository: `git clone https://github.com/fkie-cad/Logprep.git`
2. navigate into it: `cd Logprep`
3. replace the contents of the file: `quickstart/exampledata/config/pipeline.yml` with:

```yaml
version: 1
process_count: 1
timeout: 0.1

metrics:
  enabled: true
  period: 10
  cumulative: false
  aggregate_processes: false
  measure_time:
    enabled: true
    append_to_event: false
  targets:
    - prometheus:
        port: 8000

pipeline:
  - normalizer:
      type: normalizer
      specific_rules:
        - quickstart/exampledata/rules/normalizer/specific/
      generic_rules:
        - quickstart/exampledata/rules/normalizer/generic/
      regex_mapping: quickstart/exampledata/rules/normalizer/normalizer_regex_mapping.yml

input:
  mydummyinput:
    type: jsonl_input
    documents_path: tests/testdata/input_logdata/kafka_raw_event.jsonl
    repeat_documents: true

output:
  my_jsonl_output:
    type: jsonl_output
    output_file: output.file
    output_file_custom: output_custom.file
    output_file_error: output_error.file
```

4. pull the docker image: 
```bash
docker pull ghcr.io/fkie-cad/logprep:py3.11-dev-allow-repeating-events-for-dummy-inputs
```
6. run the image with: 
```bash
docker run -v "$(pwd)"/quickstart/:/home/logprep/quickstart/ -v "$(pwd)"/tests/:/home/logprep/tests/ -p 8000:8000 ghcr.io/fkie-cad/logprep:py3.11-dev-allow-repeating-events-for-dummy-inputs quickstart/exampledata/config/pipeline.yml
```
7. open the browser at: `localhost:8000`
8. wait around ten seconds and reload the browser page every now and then. or wait until you see in the console the log output `Pipeline INFO    : Started exposing metrics`, that's when you should see some logprep metrics in the browser. If you wait another ten seconds, then the metrics should update again. The reason we have to wait for the ten seconds is the metrics configuration. There we set the `period` to `10`. That's the amount logprep waits to collect and update the metric endpoint.

Also the reason why we use here the image `py3.11-dev-allow-repeating-events-for-dummy-inputs` is just so we have a simple continues input stream, besides that it is the same as the latest released logprep version. 

Hope that works and we can verify that the metrics do work on your side.
