### ISSUE TITLE
GenericAdder - Parameter "regex_fields" cannot be set

### ISSUE THREAD

**Issue by niklas-kunz** [fkie-cad/Logprep#441]
I am trying to replicate the following generic adder configuration from an example config i was given:

```
---
filter: "..."
regex_fields:
  - data_stream.dataset

generic_adder:
  add:
    event.kind: "event"

description: "..."
---
```
However, the parameter "regex_field" cannot be configured. Is the example config above out-of-date or is the parameter missing?
