### ISSUE TITLE
Pseudonymizer no validation of existing files on logprep start

### ISSUE THREAD

**Issue by dtrai2** [fkie-cad/Logprep#597]
Configuring a pseudonymizer with files that do not exist results in stacktraces.

**Expected behavior**
On logprep start there should be once an error message that logprep couldn't start because it wasn't configured properly.

**Current behavior**
Starts but repeatedly prints stacktraces / error log messages

**Steps to reproduce**
Start logprep with the following configuration: 

```yaml
input:
    dummy:
        type: dummy_input
        documents: [{"foo":"bar"}]
output:
    dummy:
        type: dummy_output
pipeline:
    - pseudonymizername:
        type: pseudonymizer
        specific_rules:
            - filter: foo
              pseudonymizer:
                  mapping:
                      foo: RE_WHOLE_FIELD_CAP
        generic_rules: []
        outputs:
            - dummy: pseudonyms_topic
        pubkey_analyst: /path/to/analyst_pubkey.pem
        pubkey_depseudo: /path/to/depseudo_pubkey.pem
        hash_salt: secret_salt
        regex_mapping: /path/to/regex_mapping.json
        max_cached_pseudonyms: 1000000
```

Do different start ups with (non)existing paths for the fields `regex_mapping`, `pubkey_analyst`/`pubkey_depseudo` and watch the different error behavior. 

**Environment**

Logprep version: 856ceaf8
Python version: 3.11.9

**Possible solution**
Validate file paths on logprep start, before the pipeline object is created.
