### ISSUE TITLE
Pseudonymizer late error on non existing regexmapping

### ISSUE THREAD

**Issue by dtrai2** [fkie-cad/Logprep#598]
If the pseudonymizer is started with a regex mapping that is not defined inside the `regex_mapping` config file logprep will start but continuously throw an error log.

**Expected behavior**
Validate and throw an error once before the actual logprep start 

**Current behavior**
Logprep continuously restarts and prints the same error message, that is also not very helpful: 

```
Pipeline1  ERROR   : ProcessingCriticalError: ProcessingCriticalError: 'str' object has no attribute 'groups' -> event was send to error output and further processing stopped, rule.id='6698c4297baeffbf06a3878c37f4f269db0015cd89e443b6510e60678a600213', rule.description='', event={'foo': 'bar'}
```

**Steps to reproduce**
Run logprep with the following pipeline:

```yaml
input:
    dummy:
        type: dummy_input
        documents: [{"foo":"bar"}]
output:
    dummy:
        type: dummy_output
pipeline:
    - pseudonymizername:
        type: pseudonymizer
        specific_rules:
            - filter: foo
              pseudonymizer:
                  mapping:
                      foo: DOES_NOT_EXIST 
        generic_rules: []
        outputs:
            - dummy: pseudonyms_topic
        pubkey_analyst: /path/to/analyst_pubkey.pem
        pubkey_depseudo: /path/to/depseudo_pubkey.pem
        hash_salt: secret_salt
        regex_mapping: tests/testdata/unit/pseudonymizer/pseudonymizer_regex_mapping.yml
        max_cached_pseudonyms: 1000000
```

**Environment**

Logprep version: 856ceaf8
Python version: 3.11.9
