### ISSUE TITLE
configuration overwrites with default values

### ISSUE THREAD

**Issue by ekneg54** [fkie-cad/Logprep#611]
example:

create these configs:

exporter-config:

```yaml 
metrics:
  enabled: true
  port: 8000
```
input-config:
```yaml
input:
  stdin:
    type: file_input
    logfile_path: /proc/1/fdinfo/0
    start: end
    watch_file: true
    interval: 1
```
output-config :
```yaml
output:
  console:
    type: console_output
```

then print the config:

```bash
logprep print exporter-config input-config output-config
```

you will see, that metrics is not enabled

if you print in different order you see metrics is enabled

```bash
logprep print input-config output-config exporter-config
```

the behaviour should be consistent
