### ISSUE TITLE
Autorule tester crashes with rules directly defined in the pipeline

### ISSUE THREAD

**Issue by ppcad** [fkie-cad/Logprep#749]
The autorule tester crashes if a rule is being defined in the pipeline config of a processor.

The following leads to an exception when runnint logprep with `unit test`:
```yaml
  - dropper:
      type: dropper
      rules:
        - examples/exampledata/rules/dropper/rules
        - filter: "test_dropper"
          dropper:
            drop:
              - drop_me
          description: "..."
```

The reason for this is that the autorule tester expects paths and not dictionaries.
