### ISSUE TITLE
Support YAML anchors and/or includes

### ISSUE THREAD

**Issue by ppcad** [fkie-cad/Logprep#791]
Rules for some processors use YAML parts that could be potentially very large and repeated within different rules.

It would be desireable if YAML parts could be defined in one place to be reuseable.

Possible solutions for this could be YAML anchors and includes.

However, YAML anchors only work within the document they are defined in and includes are not supported by default.

One could implement a custom constructor to allow YAML anchors to work in different YAML documents within the same YAML file.

Furthermore, one could implement a custom YAML constructor to support includes.

Examlple for anchors:
```yaml
rule1:
  something_large: &some_anchor
    - ...
---
rule2:
  something_large: *some_anchor
```
 
Example for includes:
```yaml
rule1:
  something_large: !include some_data.yaml
    - ...
---
rule2:
  something_large: !include some_data.yaml
```
